#!/usr/bin/env bash

: <<'Info'

   Exploit Source  :  https://exploit-db.com
   Email           :  rupture6.dev@gmail.com
   Github Link     :  https://github.com/handler/terasploit-framework

Info

if [ $# -eq 0 ]
  then
  python3 /usr/share/terasploit-framework/terasploit
  exit
else
  python3 /usr/share/terasploit-framework/terasploit $1 $2 $3 $4 $5 $6 $7 $8 $9
  exit
fi
