#!/usr/bin/env bash

clear
sleep 1

echo "Terasploit Framework - Bash :: Installation"
echo "Handler4 - Contact :: handler4.nsi@gmail.com"

echo ""
printf "[*] \033[32minstalling requirements\033[39m\n\n"
sudo apt update && sudo apt upgrade
sudo apt install python3 python3-pip git curl 
curl -O https://raw.githubusercontent.com/rupture6/terasploit-framework/master/.requirements/requirements.txt && pip3 install -r requirements.txt && rm -rf requirements.txt

echo ""
printf "[*] \033[32minstalling files on bin\033[39m\n\n"
curl -O https://raw.githubusercontent.com/rupture6/terasploit-framework/master/.install/terasploit && chmod +x terasploit
curl -O https://raw.githubusercontent.com/rupture6/terasploit-framework/master/.install/tsfupdate && chmod +x tsfupdate
sudo mv -v terasploit /usr/bin
sudo mv -v tsfupdate /usr/bin

echo ""
printf "[*] \033[32minstalling terasploit-framework files\033[39m\n\n"
git clone https://github.com/rupture6/terasploit-framework.git && sudo find terasploit-framework -type f -exec chmod +x {} \;
sudo cp -r terasploit-framework /usr/share
sudo rm -rf terasploit-framework

echo ""
printf "[*] \033[32minstallation script done!\033[39m\n\n"
echo "type 'terasploit' to run Terasploit Framework console."
